"""
Interactive setup script for Supabase configuration.
Guides user through creating .env file with credentials.
"""

import os
from pathlib import Path

def main():
    print("\n" + "=" * 60)
    print("🔧 MOVI Backend - Supabase Configuration Setup")
    print("=" * 60)
    print()
    
    backend_dir = Path(__file__).parent
    env_file = backend_dir / ".env"
    env_template = backend_dir / ".env.template"
    
    # Check if .env already exists
    if env_file.exists():
        print(f"⚠️  .env file already exists at: {env_file}")
        response = input("Do you want to overwrite it? (yes/no): ").lower().strip()
        if response not in ['yes', 'y']:
            print("❌ Setup cancelled. Existing .env file preserved.")
            return
        print()
    
    print("📋 Please have the following information ready from Supabase:")
    print("   1. Project URL (https://xxx.supabase.co)")
    print("   2. Anon Key (public API key)")
    print("   3. Service Role Key (admin key)")
    print("   4. Database URL (connection string)")
    print()
    print("💡 Find these in: Supabase Dashboard → Settings → API & Database")
    print()
    
    input("Press Enter when ready to continue...")
    print()
    
    # Collect credentials
    print("=" * 60)
    print("Enter your Supabase credentials:")
    print("=" * 60)
    print()
    
    supabase_url = input("SUPABASE_URL: ").strip()
    if not supabase_url:
        print("❌ Error: SUPABASE_URL cannot be empty")
        return
    
    supabase_anon_key = input("SUPABASE_ANON_KEY: ").strip()
    if not supabase_anon_key:
        print("❌ Error: SUPABASE_ANON_KEY cannot be empty")
        return
    
    supabase_service_key = input("SUPABASE_SERVICE_ROLE_KEY: ").strip()
    if not supabase_service_key:
        print("❌ Error: SUPABASE_SERVICE_ROLE_KEY cannot be empty")
        return
    
    database_url = input("DATABASE_URL: ").strip()
    if not database_url:
        print("❌ Error: DATABASE_URL cannot be empty")
        return
    
    # Generate random secret key for FastAPI
    import secrets
    fastapi_secret = secrets.token_urlsafe(32)
    
    # Create .env content
    env_content = f"""# Supabase Configuration
# Generated by setup_env.py
SUPABASE_URL={supabase_url}
SUPABASE_ANON_KEY={supabase_anon_key}
SUPABASE_SERVICE_ROLE_KEY={supabase_service_key}

# Database Connection
DATABASE_URL={database_url}

# FastAPI Configuration
FASTAPI_SECRET_KEY={fastapi_secret}

# Frontend Environment Variables (if needed)
VITE_SUPABASE_URL={supabase_url}
VITE_SUPABASE_ANON_KEY={supabase_anon_key}
VITE_API_BASE_URL=http://localhost:8000
"""
    
    # Write .env file
    try:
        with open(env_file, 'w') as f:
            f.write(env_content)
        
        print()
        print("=" * 60)
        print("✅ SUCCESS!")
        print("=" * 60)
        print()
        print(f"✅ .env file created at: {env_file}")
        print()
        print("🔐 Security notes:")
        print("   - .env is already in .gitignore (not committed to Git)")
        print("   - Never share your Service Role Key publicly")
        print()
        print("📝 Next steps:")
        print("   1. Run: python verify_db.py (to test connection)")
        print("   2. Run: python ../scripts/seed_db.py (to populate data)")
        print()
        
    except Exception as e:
        print(f"\n❌ Error writing .env file: {e}")
        return

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled by user.")
    except Exception as e:
        print(f"\n❌ Unexpected error: {e}")
